// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWuw1okwlKutB3SZkQbH30eplSE8eXPB0',
    appId: '1:117673821208:web:66c73bb1890b4511e76f6d',
    messagingSenderId: '117673821208',
    projectId: 'student-system-50843',
    authDomain: 'student-system-50843.firebaseapp.com',
    storageBucket: 'student-system-50843.firebasestorage.app',
    measurementId: 'G-0N1SV1R5WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChPVIjFAXJG7ZI7GJVCsEjeOReBk6JqP0',
    appId: '1:117673821208:android:979b916c5d77e1d0e76f6d',
    messagingSenderId: '117673821208',
    projectId: 'student-system-50843',
    storageBucket: 'student-system-50843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADp2BQBfMo8S6FRFPaMaZD-GXKG_g3aK8',
    appId: '1:117673821208:ios:4fb126937f3243dee76f6d',
    messagingSenderId: '117673821208',
    projectId: 'student-system-50843',
    storageBucket: 'student-system-50843.firebasestorage.app',
    iosClientId: '117673821208-hhmo95tj591jfr1untb2mt1n9kh9rgoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADp2BQBfMo8S6FRFPaMaZD-GXKG_g3aK8',
    appId: '1:117673821208:ios:4fb126937f3243dee76f6d',
    messagingSenderId: '117673821208',
    projectId: 'student-system-50843',
    storageBucket: 'student-system-50843.firebasestorage.app',
    iosClientId: '117673821208-hhmo95tj591jfr1untb2mt1n9kh9rgoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWuw1okwlKutB3SZkQbH30eplSE8eXPB0',
    appId: '1:117673821208:web:d0a4a4bfea9a9af6e76f6d',
    messagingSenderId: '117673821208',
    projectId: 'student-system-50843',
    authDomain: 'student-system-50843.firebaseapp.com',
    storageBucket: 'student-system-50843.firebasestorage.app',
    measurementId: 'G-2XGP5V6GCE',
  );
}
