// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // TODO: Put your Firebase web API key here
    apiKey: '',
    // TODO: Put your Firebase web app ID here
    appId: '',
    // TODO: Put your Firebase messaging sender ID here
    messagingSenderId: '',
    // TODO: Put your Firebase project ID here
    projectId: '',
    // TODO: Put your Firebase auth domain here
    authDomain: '',
    // TODO: Put your Firebase storage bucket here
    storageBucket: '',
    // TODO: Put your Firebase measurement ID here
    measurementId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    // TODO: Put your Firebase Android API key here
    apiKey: '',
    // TODO: Put your Firebase Android app ID here
    appId: '',
    // TODO: Put your Firebase messaging sender ID here
    messagingSenderId: '',
    // TODO: Put your Firebase project ID here
    projectId: '',
    // TODO: Put your Firebase storage bucket here
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // TODO: Put your Firebase iOS API key here
    apiKey: '',
    // TODO: Put your Firebase iOS app ID here
    appId: '',
    // TODO: Put your Firebase messaging sender ID here
    messagingSenderId: '',
    // TODO: Put your Firebase project ID here
    projectId: '',
    // TODO: Put your Firebase storage bucket here
    storageBucket: '',
    // TODO: Put your Firebase iOS client ID here
    iosClientId: '',
    // TODO: Put your Firebase iOS bundle ID here
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    // TODO: Put your Firebase macOS API key here
    apiKey: '',
    // TODO: Put your Firebase macOS app ID here
    appId: '',
    // TODO: Put your Firebase messaging sender ID here
    messagingSenderId: '',
    // TODO: Put your Firebase project ID here
    projectId: '',
    // TODO: Put your Firebase storage bucket here
    storageBucket: '',
    // TODO: Put your Firebase macOS client ID here
    iosClientId: '',
    // TODO: Put your Firebase macOS bundle ID here
    iosBundleId: '',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    // TODO: Put your Firebase Windows API key here
    apiKey: '',
    // TODO: Put your Firebase Windows app ID here
    appId: '',
    // TODO: Put your Firebase messaging sender ID here
    messagingSenderId: '',
    // TODO: Put your Firebase project ID here
    projectId: '',
    // TODO: Put your Firebase auth domain here
    authDomain: '',
    // TODO: Put your Firebase storage bucket here
    storageBucket: '',
    // TODO: Put your Firebase measurement ID here
    measurementId: '',
  );
}
